# Generated by Django 4.1.7 on 2023-03-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodel',
            name='category',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('sql', 'SQL'), ('web', 'WEB'), ('others', 'Others')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tutormodel',
            name='links',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
